openapi: 3.0.0
info:
  title: Photo Rating API
  version: 1.0.0
paths:
  /api/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
        '400':
          description: Email already registered
        '500':
          description: Registration failed
  /api/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
        '400':
          description: Invalid credentials
        '500':
          description: Login failed
  /api/forgot-password:
    post:
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset token generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '404':
          description: User not found
        '500':
          description: Forgot password failed
  /api/reset-password:
    post:
      summary: Reset user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Password reset successful
        '400':
          description: Invalid or expired token
        '500':
          description: Reset password failed
  /api/photo/upload:
    post:
      summary: Upload a photo (requires authentication)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
      responses:
        '201':
          description: Photo uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  photoId:
                    type: string
        '400':
          description: Invalid file type or size
        '401':
          description: Unauthorized
        '500':
          description: Photo upload failed
  /api/photo/rate:
    get:
      summary: Get photos to rate (requires authentication)
      responses:
        '200':
          description: List of photos to rate
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    filePath:
                      type: string
        '401':
          description: Unauthorized
        '500':
          description: Failed to fetch photos
    post:
      summary: Rate a photo (requires authentication)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
                score:
                  type: number
                  minimum: 1
                  maximum: 5
      responses:
        '200':
          description: Photo rated successfully
        '400':
          description: Invalid score or already rated
        '401':
          description: Unauthorized
        '404':
          description: Photo not found
        '500':
          description: Rating failed
  /api/photo/evaluate/add:
    post:
      summary: Add photo to evaluated list (requires authentication)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
      responses:
        '200':
          description: Photo added to evaluated
        '401':
          description: Unauthorized
        '500':
          description: Failed to add photo
  /api/photo/evaluate/remove:
    post:
      summary: Remove photo from evaluated list (requires authentication)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
      responses:
        '200':
          description: Photo removed from evaluated
        '401':
          description: Unauthorized
        '500':
          description: Failed to remove photo
  /api/photo/statistics/{photoId}:
    get:
      summary: Get photo statistics (requires authentication)
      parameters:
        - in: path
          name: photoId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Photo statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalRatings:
                    type: number
                  averageScore:
                    type: string
                  scores:
                    type: array
                    items:
                      type: number
        '401':
          description: Unauthorized
        '403':
          description: Access forbidden
        '404':
          description: Photo not found
        '500':
          description: Failed to fetch statistics